version: "3"
services:
  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper
    restart: always
    networks:
      - elk-net
  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CREATE_TOPICS=app-log-collector:1:1,error-log-collector:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    container_name: kafka
    restart: always
    networks:
      - elk-net
  kafka-manager:
    image: sheepkiller/kafka-manager:1.3.0.4
    ports:
      - 9000:9000
    depends_on:
      - zookeeper
      - kafka
    environment:
      - ZK_HOSTS=zookeeper:2181
    container_name: kafka-manager
    restart: always
    networks:
      - elk-net
  filebeat:
    entrypoint: bash -c '/usr/local/bin/docker-entrypoint -e -c /usr/share/filebeat/filebeat.yml'
    image: docker.elastic.co/beats/filebeat:8.1.1
    #        ports:
    #            - "8080:80"
    volumes:
      - "/opt/data/filebeat_data/filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - "/opt/data/filebeat_data/logs/:/var/log/filebeat/"
    depends_on:
      - kafka
    container_name: filebeat
    restart: always
    networks:
      - elk-net
  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
    volumes:
      - "/opt/data/elasticsearch_data/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "/opt/data/elasticsearch_data/plugins:/usr/share/elasticsearch/plugins"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms64m -Xmx200m
    container_name: elasticsearch
    restart: always
    networks:
      - elk-net
  logstash:
    image: docker.elastic.co/logstash/logstash:8.1.1
    #        ports: 9600 5044
    volumes:
      - "/opt/data/logstash_data/pipeline/:/usr/share/logstash/pipeline/"
    depends_on:
      - kafka
      - elasticsearch
    container_name: logstash
    restart: always
    networks:
      - elk-net
  kibana:
    image: kibana:7.6.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    container_name: kibana
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - elk-net
networks:
  elk-net:
    driver: bridge
